//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCategories
    {
        public BusinessCategories()
        {
            this.Interests = new HashSet<Interest>();
            this.Businesses = new HashSet<Business>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
