//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public int BusinessID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sensor_Id { get; set; }
        public int BusinessCategoriesId { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual Users_Admin Users_Admin { get; set; }
        public virtual Users_Owner Users_Owner { get; set; }
        public virtual BusinessCategories BusinessCategory { get; set; }
        public virtual City City { get; set; }
    }
}
