//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Interests = new HashSet<Interest>();
            this.OrderedCoupons = new HashSet<OrderedCoupon>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double OriginalPrice { get; set; }
        public double DiscountPrice { get; set; }
        public string ExperationDate { get; set; }
        public Nullable<double> AvarageRanking { get; set; }
        public int MaxNum { get; set; }
        public int Business_BusinessID { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupons { get; set; }
    }
}
