//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendedCoupon
    {
        public int Id { get; set; }
        public int Source { get; set; }
        public string Link { get; set; }
        public string Customer_UserName { get; set; }
        public bool Approved { get; set; }
    
        public virtual Users_Customer Users_Customer { get; set; }
        public virtual Coupon Coupon { get; set; }
    }
}
