//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.Businesses = new HashSet<Business>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Coordinates { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
