//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Owner
    {
        public Users_Owner()
        {
            this.Businesses = new HashSet<Business>();
        }
    
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
