//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Sensor = new HashSet<Sensor>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Sensor> Sensor { get; set; }
        public virtual Users_Customer Users_Customer { get; set; }
    }
}
