//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Customer
    {
        public Users_Customer()
        {
            this.OrderedCoupons = new HashSet<OrderedCoupon>();
            this.Recommendations = new HashSet<Recommendation>();
            this.Visits = new HashSet<Visit>();
        }
    
        public string UserName { get; set; }
    
        public virtual ICollection<OrderedCoupon> OrderedCoupons { get; set; }
        public virtual ICollection<Recommendation> Recommendations { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
