//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public bool Blocked { get; set; }
    
        public virtual Users_Admin Users_Admin { get; set; }
        public virtual Users_Customer Users_Customer { get; set; }
        public virtual Users_Owner Users_Owner { get; set; }
    }
}
