//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Customer
    {
        public Users_Customer()
        {
            this.OrderedCoupons = new HashSet<OrderedCoupon>();
            this.RecommendedCoupons = new HashSet<RecommendedCoupon>();
            this.Sensors = new HashSet<Sensor>();
            this.Interests = new HashSet<Interest>();
        }
    
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupons { get; set; }
        public virtual ICollection<RecommendedCoupon> RecommendedCoupons { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
    }
}
