//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int Location_Id { get; set; }
        public string CustomerVisit_Visit_UserName { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Users_Customer Users_Customer { get; set; }
    }
}
